# Generated by Django 3.2.13 on 2022-05-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
