# Generated by Django 3.2.13 on 2022-05-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_songdelete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongDelete',
        ),
        migrations.AddField(
            model_name='song',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
