# Generated by Django 3.2.13 on 2022-05-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20220515_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['added_on']},
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
