# Generated by Django 3.2.13 on 2022-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_auto_20220526_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
