# Generated by Django 3.2.13 on 2022-05-08 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220508_2024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
